name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    uses: MaikoTan/workflows/.github/workflows/publish-vscode-extension.yml@master
    secrets:
      OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
      VS_MARKETPLACE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}
